# Generated by Django 4.0.4 on 2022-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='batch_value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock_itemcreation',
            name='expiry',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock_itemcreation',
            name='expiry_dates',
            field=models.DateField(default='null'),
        ),
        migrations.AddField(
            model_name='stock_itemcreation',
            name='track_date',
            field=models.DateField(default='null'),
        ),
    ]
