# Generated by Django 4.0.4 on 2022-09-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_stock_itemcreation_batch_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='expiry_dates',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='track_date',
            field=models.DateField(),
        ),
    ]
