# Generated by Django 4.0.4 on 2022-09-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_stock_itemcreation_expiry_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='batch_value',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='expiry_dates',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='track_date',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
