# Generated by Django 4.0.4 on 2022-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_stock_itemcreation_batch_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='batch_value',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
