# Generated by Django 4.0.4 on 2022-09-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_stock_itemcreation_batch_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='batch_value',
        ),
    ]
