# Generated by Django 4.0.4 on 2022-09-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_create_stock_itemcreation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_itemcreation',
        ),
    ]
