# Generated by Django 4.0.4 on 2022-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_stock_itemcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_itemcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('under', models.CharField(max_length=100, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('batches', models.CharField(max_length=10, null=True)),
                ('cost_tracking', models.CharField(max_length=10, null=True)),
                ('expiry', models.CharField(max_length=100, null=True)),
                ('gst_applicable', models.CharField(max_length=100, null=True)),
                ('typ_sply', models.CharField(max_length=100)),
                ('set_alter', models.CharField(max_length=100)),
                ('rate_of_duty', models.IntegerField()),
                ('godown', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('track_date', models.CharField(max_length=100, null=True)),
                ('expiry_dates', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('per', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Create_stock_itemcreation',
        ),
    ]
