# Generated by Django 4.0.4 on 2022-09-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_stock_itemcreation_delete_create_stock_itemcreation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='godown',
        ),
    ]
