# Generated by Django 4.0.4 on 2022-09-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_stock_itemcreation_godown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='expiry_dates',
        ),
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='track_date',
        ),
    ]
